<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.eta</groupId>
        <artifactId>eta-system</artifactId>
        <version>11.5</version>
    </parent>

    <artifactId>eta-gui-shared-backend</artifactId>
    <dependencies>
        <dependency>
            <groupId>com.eta</groupId>
            <artifactId>eta-link</artifactId>
            <version>11.5</version>
        </dependency>
        <dependency>
            <groupId>com.eta</groupId>
            <artifactId>eta-util-java</artifactId>
            <version>11.5</version>
        </dependency>
    </dependencies>

</project>